FROM node:20-alpine AS builder

WORKDIR /app/client

COPY client/package.json ./
RUN npm install

COPY client/ ./
RUN npm run build

FROM node:20-alpine

WORKDIR /app/client

COPY --from=builder /app/client/dist ./dist
RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]
